class Strings {
  static const String APP_NAME = "ASTROBUSH";

  static const List<String> BUS_NAMES = [
    "Koc",
    "Boga",
    "Ikizler",
    "Yengec",
    "Aslan",
    "Basak",
    "Terazi",
    "Akrep",
    "Yay",
    "Oglak",
    "Kova",
    "Balik"
  ];

  static const List<String> BUSH_DATES = [
    "21 Mart - 20 Nisan",
    "21 Nisan - 21 Mayıs",
    "22 Mayıs - 22 Haziran",
    "23 Haziran - 22 Temmuz",
    "23 Temmuz - 22 Agustos",
    "23 Agustos - 22 Eylül",
    "23 Eylül - 22 Ekim",
    "23 Ekim - 21 Kasım",
    "22 Kasım - 21 Aralık",
    "22 Aralık - 21 Ocak",
    "22 Ocak - 19 Subat",
    "20 Subat - 20 Mart"
  ];

  static const List<String> BUSH_GENERAL_FATURES = [
   "Koç burcu yeni başlangıçları ve doğumu temsil eder. Koç insanı doğal, içgüdüsel, taze saf ve hayattan zevk alan bir yapıdadır. Çekingenlik duygusu ona yabancıdır. Koç burcunun başlıca niteliği, her zaman kesin olmasa da olumlu bir zeka düzeyi ve yüksek beyin kapasitesi göstermesidir. Koç insanı anlık tepkiler gösterir, bütün cesareti, enerji ve yaratıcılığı anlık bir meydan okumadır. Hiçbir şeyden çözülmemiş sorunlar kadar nefret edemez. Uzun süre çabalaması gerektiğinde sık sık tahammülünü kaybeder.\n\n Hayat onlar için heyacanlı bir maceradır. Her yönüyle hayatın tadını çıkarmak isterler. Bazıları koçta bencillik niteliklerinin fazla olduğunu düşünür. Çünkü o, başkalarının kendi hakkında ne düşündüğünü, hareketlerinin onaylanıp onaylanmadığını öğrenmeye çalışmaz. Başkalarının onu bildiğinden şaşırtmasına izin vermez. Koç yaşamın her anında daima bir meydan okuma davranışları gösterir.\n\nKoç kendini sınırlanmış ve başarısı engellenmiş hissettiği anda, koçun içindeki savaşçı tabiat birden bire canlanır. Bir koça bir şeyi beğendirmek zor ve yorucu bir iştir. Bununla birlikte koçun yardımseverliğini reddettiğinizde karşınızda yaralanmış ve hayal kırıklığına uğramış bir insan bulursunuz. Çünkü aldırmaz görünmesine rağmen o, aşırı derecede hassas ve duygusaldır. Paylaşma ve yardım teklifinin reddi durumunda tepkisi depresif bir halde içe dönme olabilir, fakat kendini ilkel bir öfke ve kızgın bir hava içine sokar.\n\nKoçlar ıvır zıvır ile uğraşmayı başkalarına bırakır. Devamlı yenilik peşinde olma dürtüsünü hayat boyu bastıramazlar. Aksi halde kişiliklerini kaybederler. Açıklık ve dürüstlükleriyle ara sıra diğer insanları yaralarlar. Aslında yaralama düşüncesi akıllarından bile geçmez.",

   "Boğa umudun burcudur. Boğasız bir burçlar kuşağı düşünülemez. Sabırlı, sorumluluk sahibi boğa burçlar içinde en insancıl ve sıcakkanlı olanıdır. Boğa insanı ruhsal varlığına olduğu kadar maddesel varlığına da bağlıdır. Dış görünüşü ile sakin ve tepkisiz görünen boğa insanı kışkırtıldığında kızgın bir boğa gibi saldırıya geçer. Eyleme geçmekte ağır kanlı fakat kızgınlıkta zaptedilmesi güç bir mizaç sayılır. Boğaların dışa yansıyan özellikleri arasında sabırlı olmak, elinden iş gelmek ve mülkiyetçilik sayılabilir. Sabırlı insan genellikle sakindir, durgundur, gayretlidir, soğukkanlıdır.\n\nBoğalar azimli ve kararlıdır. Borçlarında ve ödevlerinde sıkı bir doğrucudur. Boğa burcunun mülkiyetçiliği hem maddiyata hemde insanlara uzanır. Genellikle kibar, uyumlu, bencil olmayan ve çevresine özenlidir. Doğal olarak sabrının sınırlarını zorlayan bir davranış karşısında bir yanardağ gibi patlayabilir. Boğalar rahatsız olacakları bir durumdan kaçınmaya çalışırlar. Kıskançlık, oburluk ve maddiyatçılığa karşı dikkatli olmalıdırlar.\n\nBoğa insanları çocukluğundan itibaren sevgi ve aşırı ilgiye ihtiyaç duyarlar. Bu yetişkin olduğu zamanda devam eder. Karşı cinse olan bağlılığı da biraz bu yüzdendir. Fiziksel olarak çok çekicidirler ve doğanın bu hediyesinin bilincindedirler. Bakımlı görünmeye büyük özen gösterirler. Onlar için kendilerine bakmak çok anlamlı bir iştir. Kendisini göstermek için yaptığı hareketlerin hepsi çevresinin dikkatini çekmek içindir. Kesinlikle konuşkan, çok sesli ve düşüncelerini açıkça belirten iyi bir dinleyicidir.\n\nBoğalar genelde sabit fikirlidirler. Hayatı siyah beyaz bir resim gibi görürler. Aynı zamanda yakın çevresindeki insanlarla birlikteyken anlaşmaya daha yatkındırlar. Boğa erkeği manevi olan herşeye bağlı olmasına rağmen bir kadının bütün entellektüel yanını ortaya koymasına da çok değer vermez. Bu durumda kadın erkeğin kayıtsızlığını ifade eden soğuk bakışlara maruz kalır. Arasıra arkadaşlarını beklenmedik araklarla şaşırtmanız, şimdiye kadar söylenenlerin bir inkarı değildir. Bu sadece duygularınız incindiğinde geçerli olur.",

   "İkizler kişiliği her işe yatkın çift karakterli bir kişiliktir. Çabuk düşünürler, çabuk hareket ederler. Bir an neşeli bir an mutlu olabilirler ve başkaları onları anlamakta zorluk çeker. Bu burcu kapsayan özellik iletişime öncülük yanında akıl ve zeka ile değişim sayılabilir. İletişimden anlaşılan konuşmak ve öğrenmek sanatıdır.\n\nAkıl ve zeka özellikleri arasında yargı gücü, mantık ve entellektüellik, gerçekleri kavramak ve idrak zenginliği sayılabilir. Değişim özelliğinde de çabucak eyleme geçebilmek, yeni fikirlere ve oluşumlara yatkınlık, esneklik, seyahat meyli, ileri gitmek hırsı ve elinden iş gelmek yeteneği anlaşılabilir.\n\nİkizlerin mizacı söyledikleri anlaşılan ve eleştirilmekten yılmayan kişilikte yetenekli ve nazik yaradılışlıdır. Fakat bazen bu yoğun özellikler aşırı bir görünüm gösterebilir. İkizler kişiliği gevezelik , çekingenlik, kararsızlık, kurnazlık ve hilebazlık, bencillik ve vefasızlık karşısında korunmayı becerebilmelidir. Burçta güneş çok iyi konumdadır. Kişinin çevresine yardımı konusunda ilerici bir dikkat verir. Fakat bunu akrabalarından çok arkadaşları kullanır.\n\nİkizler genelde ilgi odağıdır ve yanında kendini çok iyi hisseden, entellektüel insanlarla dostluk kurar. İki ya da üç şeyi bir arada yapmak ona zor gelmez. Kişilikleri ve yaşam tarzları onların tek ifadesidir ama aynı zamanda cazibeli, liderlik yeteneğine sahip, neşeli, gayretlerini endişeli ve sorunlu olduklarında bile kaybetmeyen iyimser insanlardır. Keskin zekası ve akıllı düşüncelerine rağmen aslında iflah olmaz bir romantik, idealist ve hayalcidirler. Fantazileriniz sizi en büyük spekülasyonlara bile insandırır.\n\nİkizler kolay kolay bir öğüdü, haklı bir hükmü veya iyi bir teklifi kabul edemez. Büyük bir beceriyle haraketini mazur gösterir ve böylece her tatışmayı söndürür. Çift yönlü kişliği onu tekrar çok yönlü ilgi ve isteklerin heyecanlı dünyasına yönlendirecektir. Gerçek olmayan aşklara duyduğunuz tepki yüzünden duygusuz ve soğuk görünebilirsiniz. Şaşkınlıkların etkisinden hemen kurtulursunuz. Mantıklı bir durumun ispatını hemen kabullenmediğiniz ve bu durum üzerinde uzun süre durmadığınız için sizi seven insanları hayal kırıklığına uğratabilirsiniz.",

   "Yengeçlerin çelişkili yapıları dillere destan bir durum. Gülmeyi seversiniz, mizah duygunuz güçlü, arkadaş canlısı, sempatik, yardımsever bir yoldaşsınız. Sizi yüzeysel olarak tanıyan biri, zaman zaman melankolik bir ruh haliyle acı çektiğinizi düşünebilir. Duygusallık en başlıca özelliğiniz. Başkalarına karşı anlayışlı davranmak ve itina göstermek de dışa vuran belirgin özelliklerinizden.\n\nYengeç burcu insanı mantıktan fazla sezgiye bağlı olmaya meyillidir. Ruhları sakin yumuşak ve duyarlıdır. Bu duyarlı yapıya karşın yengeçler dışa karşı korunmalarını sağlayan kalın bir kabukla örtülüdürler. Ay tarafından yönetilen tek zodyak burcu yengeçtir. Ay ve yengeç genellikle birbirlerinin olumlu özelliklerini daha da güçlendirirler. Bununla birlikte toyluk ve aşırı güven meyli ortaya çıkabilir.\n\nYengeçlerin özellikleri iş yaşamında çevresi ile sorunlar yaşamalarına neden olabilir. Bazen ağzı sıkı olmak da yanlış yorumlara neden olur. Yangeçler ancak sevgi ile yönetilebilirler. Aşık bir yengeçin yapamayacağı şey yoktur. Burçlar kuşağında en iyi aşçılar bu burçtan çıkar. Dostlarına ilgi ve yakınlık gösterirler.\n\nİş ilişkisinde arkadaş canlısı ve sakin olurlar. Huysuzluk ve güvensizlik adeta yengeçlerin en büyük tehlikeleridir. Bu konuda onları uyarıyoruz. Güneşin yengeç burcunda olması esasen yaşam savaşı için iyi bir görünüm sayılmaz. Kişiyi tembelleştirir veya rüyalar aleminde yaşatır.",

   "Aslan kraldır, önderdir. Başkalarının yaşantılarını da onlar adına düzenlemek isterler. Her şeye karışırlar, kibirlidirler. Bu nedenle onları tanımlayan sözcük 'Yönetirim' dir. Yaşam sahnesinde her zaman parlayarak, odak noktası olmak isterler. Organizasyon güçleri çok fazladır. İsteklerini başkalarına kabul ettirmek, onlar için yaşamlarının 'olmazsa olmaz' şartıdır.\n\n İyi zamanlarında etkileyici, güler yüzlü, başkalarına yardım etmeyi seven ve bunu kendine görev sayan Aslan'lar sevimli ve iyimser kişilerdir. Ona karşı hatalı davransanız bile, size olgun bir şekilde tepki verir. Fakat; Sabrı taştıktan sonra, dürüst ve mert, gerektiğinde sert bir şekilde tavır gösterir. Zor günlerinde şansları onlara her zaman yardım eder. Yönetici gezegenleri Güneş onları en karanlık günlerinde aydınlığa çıkarır. Eğitimsiz ve gelişmemiş Aslan tipleri çekilmez olurlar. Her konuda sahip olduklarından daha fazlası varmış gibi davranırlar.",

   "Son derece titiz olan başak burcu insanları, özensiz hiçbir şeye tahammül edemiyorlar. Sık bulundukları her ortamın hijyenine ekstra özen göstermelerinin yanı sıra, anlık bulundukları bir yerin bile temiz olması konusunda hassas davranıyorlar. Başak burçları işlerinde gösterdikleri üstün gayret ve özveri ile çok iyi yerlere gelmeyi başarıyor. Para kazanma hırsından dolayı hemen hemen her meslekte başarılı olabiliyorlar. Çünkü başak burçları her işin altından kalkacak potansiyele sahip olabiliyorlar.\n\nBaşak burçlarının çalışkan yapıları, zekaları ile birleştiği zaman başarılı ve tanınır iş insanı olarak toplumda öne çıkabiliyorlar. Zihinleri kimi zaman negatif durumlara odaklanıyor ve bu durumda Başak burçlarının kuruntuları ortaya çıkıyor. Kurdukları düşüncelerden dolayı kendi enerjilerini dibe çekmeyi başarıyorlar. Bunu çoğu zaman kontrol altına almayı başarsalar da kimi zaman beceremeyip tüm gün mod düşüklüğüyle gezebiliyorlar.\n\nHer zaman gerçekçi davranışları ve düşünceleri ile dikkat çeken başak burçları, boş hayallere kapılmıyor. Her şeyden önce kötü ihtimalleri düşündükleri için yaptıkları işleri güzel yönetiyorlar. Bu durum ise hem patronların hem de çalışanların gözünde güvenilir olmalarını sağlıyor. Arkadaş ortamında da oldukça sevilen bir burç oluyorlar. Evli başak burçları hem partnerine hem de çocuklarına büyük önem veriyor. Ne kadar yoğun olurlarsa olsunlar, kendilerine bakmayı ve bakımlı görünmeyi ihmal etmiyorlar.\n\nBaşak burçları her daim giyim ve kuşamlarına dikkat etmeyi seviyorlar. Her şeyin uyum içerisinde olması onları mutlu ediyor. Evin dizaynı, ofis ortamının düzenli ve tertipli olması vb. detaylar onlar için büyük önem arz ediyor. Bunun yanı sıra, her konuda mükemmele odaklı oluyorlar. O sebeple, yaşamlarında mutluluğu yakalamaları zor olabiliyor.",

   "Dış görünüşlerine oldukça önem vermeleri ile bilinen Terazi burçları bulundukları her ortamda dikkatleri üzerine çekmeyi başarırlar. Her zaman pozitif enerji saçarlar, nazik ve güler yüzlü insanlardır. Terazi burcunun yönetici gezegeninin Venüs olması nedeniyle hem Terazi erkeklerinde hem de kadınlarında karşı konulamaz bir çekicilik vardır. Terazi burcu olan birisi ile tanıştığınızda etrafa yaydığı pozitif enerjiden etkilenmemeniz neredeyse imkansızdır. Tam anlamıyla sosyal kelebekler olarak adlandırabileceğimiz Terazi burçları sevdikleriyle birlikte vakit geçirmekten son derece keyif alırlar. Yaşamlarında her zaman denge ararlar ve onlar için her zaman her şey eşit olmalıdır. Hava grubu olan terazi burçlarının dengesi herhangi bir nedenle bozulduğunda ciddi kararsızlıklar yaşamaları mümkündür. Haksızlığa en ufak bir tahammülleri olmayan Terazi burçları için herhangi birine ayrımcılık yapmak söz konusu bile değildir. Sanata ve estetiğe de oldukça düşkün olan Teraziler özel yaşamlarında da konforlarına çok önem verirler. Bu da bazen iş hayatında tembel olmalarına neden olabilir. Hem ikili ilişkilerinde hem de iş yaşamında oldukça kibar insanlardır.\n\nTerazi burçlarının en iyi anlaştığı burç kesinlikle İkizlerdir. Bir Terazi ve İkizlerin dostluğu sadece kendilerine değil etrafındaki insanlara da oldukça keyif verir. Aynı zamanda Teraziler; Kova, Aslan, Yay ve Koç burçları ile de oldukça iyi anlaşırlar. Özellikle, başlarda bir araya gelmeleri zor gibi gözükse de aralarındaki uyum ve dengeyi yakalamayı başardıklarında Terazi ve koç burcu birbirleri için mükemmel bir partner hatta eş olabilme kapasitesine sahiptir. ",

   "Zodyak’ın su elementine bağlı burçlarından biri olan Akrep burcu iki gezegenin etkisi altındadır. Gücün ve yenilenmenin gezegeni olan Plüton ve savaş gezegeni Mars. Plüton, Akrep burçlarına mükemmel bir kavrayış ve deri bir gizem vermişken Mars ise dayanıklılık ve kontrol duygusunu vermiştir. Genel olarak Akrep burçları gizemli olmaktan ve gizemli olan şeylerden çok hoşlanırlar. Tehlikeli bir hava sezdiklerinde içgüdüsel olarak o ortama doğru çekilir yani tehlikeyi severler. Samimiyetsizlik, özel hayatlarının deşilmesi ve özel alanlarını başkaları ile paylaşmak zorunda kalmak ise en sevmedikleri şeyler arasındadır.\n\nAkrep burçlarının bilinen en olumlu özellikleri; bir konu hakkında derinlemesine bilgi sahibi olmaları, disiplinli hareket etmeleri, dikkatli ve sabırlı olmalarıdır. Akrep burçları sır tutma konusunda en güvenilir burçlardan biridir. Tam anlamı ile gerçek bir dost ve sırdaş arıyorsanız o kişi kesinlikle bir Akrep burcu olacaktır. Oldukça cazibeli kişiler olan Akrep burçlarının sezgileri son derece güçlüdür. Eğer bir akrep burcu herhangi bir konuda bir şey sezdi ise onu mutlaka dinlemelisiniz. Tutkulu ve iddialı olmak Akrep burçlarının vazgeçilmez özelliklerindendir. Her zaman hayallere değil o hayallerin gerçeğe dönüşmesi için hedefe odaklanırlar ve bu özellikleri hırslı yapılarının temelini oluşturur. Akrep burçlarının duygularını anlamak neredeyse imkansızdır. Duygularını gizli tutmakta tam bir ustadırlar ve en yoğun yaşadıkları duygular hakkında bile ser verip sır vermezler.",

   "Yay burcu özellikleri kişisel, fiziksel, duygusal ve davranışsal olarak kişileri etkileyebiliyor. Yay burcunun özellikleri nelerdir, nasıl karakteristik yapıya sahiptirler gibi soruların cevabı genel olarak özgürlükçü olarak yanıt bulabiliyor. Değişken bir burç olan yay elementi ateş. Hareketli özelliğe sahip yay burcunun gezegeni Jüpiter. Yay burcunun rengi mor ve turkuaz. Burcun uğurlu yaşı ise firuze ve mavi topaz olarak karşımıza çıkıyor. Yay burcunun şanslı sayısı 3. Şanslı günü Perşembe olan burcun karşıt burcu ikizler. Yay burcu madeni kalay. Leylak, karanfili menekşe ve gül yay burcunun bitkileri olarak karşımıza çıkıyor. Yay burcunun ağaçları meşe, huş kayısı ve kestane. Yay burcunu çevreleyen yaşamsal olgular bu şekilde seyrediyor. Kişisel özelliklere etki eden burçlar kişilerin karakterlerinde belirleyici nitelikleri öne çıkarıyor. Yay burcu kişilerin genel kişisel özellikleri içerisinde öne çıkan özgür ruhlu olmaları. Heyecanlı kişiliğe sahip yay burçları kişiler arası iletişimde cana yakın olarak dikkat çekiyor. Yaşamlarından ders çıkaran yay burçları hatalarını tekrarlamayan karaktere sahip. Pratik becerilere sahip yay burçları oldukça kıvrak bir zekaya sahip. Kısıtlanma gibi durumlarda tahammülsüz olan yay burçları risk alma konusunda cesur. Yay burçları araştırmacı yapıda ve keşfetmeyi seven özelliklere sahip. İçgüdülerine güvenen yay burçları durum ve insan okuma konusunda oldukça başarılı. Çabuk sıkılan yay burçları sürekli değişken bir yaşam içerisinde olmayı amaç ediniyor. Yenilikçi ve her zaman denemeye açık yaylar meraklı olarak karşımıza çıkıyor. Yay burçlarının fiziksel özellikleri genel olarak uzun boy ve ince yapılı oluyor. Atletik vücut yapısındaki yay burçları karakteristik bir surata sahip oluyor. Yüz ifadeleri ile kararlılık izlenimi yayan yay burçları aynı zamanda karşılarındaki kişilere güven veriyor. Yay burçları karşılarındaki kişileri jest ve mimikleri ile etkileyebiliyor. Farklı tarzlar denemekten çekinmeyen yay burcu kişiler bir ortamda hemen fark edilebiliyor. Yay burçları duygu durumlarını dışarıya yansıtma da oldukça açık kişiler. Hissettikleri duyguları gizlemek yerine açıkça yaşamayı tercih ediyorlar. Yay burcu kişiler güven veren ve dinleyici kişiler. Sıcakkanlı olan yaylar arkadaş edinmek konusunda başarılı. ",

   "Oğlak burçları liderlikleri ile öne çıkan burçlar. Toprak elementine sahip oğlak burcunun gezegeni Satürn. Oğlak burcu renkleri, kurşuni, kahverengi ve yeşil olarak karşımıza çıkıyor. Uğurlu taşları bulunan oğlak lal ve kuvartz taşlarını sahipleniyor. Aynı zamanda oğlak burcu taşlarından biri kehribar. Oğlak burcunun şans sayısı sekiz. Cumartesi şanslı günü olan oğlakların karşıt burcu ise yengeç. Oğlağın madeni kurşun. Siyah gül, kamelya ve kasımpatı bitkileri ile bağdaşan burç çam ve söğüt gibi ağaçlar ile kavak ve karaağaç ağaçlarını benimsiyor. Oğlak burçlarının kişisel özellikleri içerisinde disiplin oldukça önem taşıyor. Oğlak burcu özellikleri nelerdir sorusunu yanıtlayan en dikkat çekici özellik çalışkanlık oluyor. Ruhsal erişkinliği tamamlanmış kişiler olan oğlak burçları kontrollü yaşamayı tercih ederler. Maddi konularda oldukça mantıklı hareket eden oğlak burçları iş hayatında öncü ve lider olarak karşımıza çıkıyor. Gelecek ve geçmişe çok fazla takılı kalan oğlak burçları çok düşünceli bir yapıda. Oğlak burçları gelecekleri için kolay motive olamıyor. Görev bilinci ile donanmış oğlak burçları plan yapmak ve plana uymak konusunda zorluk yaşıyor. Plan yapmak konusunda zorluk yaşayan oğlaklar görev verildiğinde ve proje tasarlanması istendiğinde buna uygun planlar yaparak başarılı sonuçlar elde edebiliyor. Oğlak burçları ödev ahlakını benimseyen karakterler. Yaratıcı tarafları da sorumluluk bilinci ile ortaya çıkıyor. Oğlak burçları özellikleri ile baskın karakterler olarak karşımıza çıkıyor. İletişimi yönlendiren ve içinde bulunduğu ortamda odak kişi olan burç. ",

   "Kova burcu özellikleri neler sorusunu yetenekli ve entelektüel şeklinde yanıtlayabilirsiniz. Kovalar genel kültür konusunda diğer burçların önüne geçiyor. Sanat ile uğraşmayı seven kova burçları estetikten anlayan bir göz zevkine sahip. Algıları oldukça açık olan kovalar bir sosyal ortamdaki gün yüzüne çıkmayan olayları tespit edebiliyor. Fark edilmeyeni fark etmek gibi yetileri olan kovalar güzel mekanlar bulmak konusunda iyi. Arkadaşlık konusunda temkinli olan kovalar iyi karakter sahibi insanları seçiyor. İnsanlara güvenmeleri çok uzun sürelere yayılan kovalar incinmekten ve hayal kırıklığına uğramaktan çok korkuyor. Kovaların genel özellikleri ile birlikte yaşam içerisinde işaret ettikleri bazı olgular var. Hava elementini benimseyen kova Uranüs gezegeni burcu. Turuncu ve yeşil gibi renkler kova burcu renkleri olarak karşımıza çıkıyor. Aynı zamanda kova renkleri arasında gece mavisi bulunuyor. Kova burcuna sahip kişilerin talihli ve verimli günleri pazar. Birçok uğurlu sayısı bulunan kova burcunun öne çıkan sayısı on bir. Yeşim kovanın uğurlu taşlarından biri. Obsidyen ve ametist taşları da kovanın taşı olarak niteleniyor. Kovalar fiziksel özelliklerinden çok konuşma, hal ve tavırları ile insanları etkilemeyi başarıyor. Bağımsız karakter yapısına sahip kovalar özgüveni yüksek ve adil olarak öne çıkıyor. Kovaların adalet duygusu oldukça gelişmiş. İnsani yönleri yüksek kovalar olayları objektif olarak değerlendirme konusunda başarılı. ",

   "Duyarlılık konusunda diğer burçlardan daha hassas olan balık duygusallığı ile biliniyor. Balık burcunun duygusallık ile birlikte birçok dikkat çekici özelliği var. Olaylar karşısında duruşları, tepkileri ve olayları yönetme biçimleri ile balıklar imrenilen burçlar. Aile, arkadaşlık ve aşk ilişkileri de olukça sansasyonel. Tüm duyguları zirvede yaşayan balık burcu haksızlığa tahammül etmeyen bir yapıda. İkna konusunda yetenekli bir burç. Balık burcu erkekleri ve kadınları arasında büyük farklar bulunmuyor. İlişkileri ile benzerlik gösteren balık kadınları ve erkekleri hayatın tadını çıkarmak ve anı yaşamak konusunda diğer burçların önüne geçiyor. Kritik kararları alabilme balık burcu için oldukça kolay. El attığı her konuda başarılı olabilen balık burçları şanslı ve şanssız anları dönem olarak yaşayabiliyor. Balık burcu özellikleri neler, karakter ve kişisel olarak nasıl farklılıklara sahip sorularını yanıtlamak için iç ve dış dünyasını analiz etmek gerekiyor. Balık burcunun iç ve dış dünyası birbirinden oldukça farklıdır. Güçlü görünmek için duygularını çoğu zaman bastırmayı deneyen balık burcu yoğun duygularının pençesinden kurtulamıyor. Balık duyguları ile savaşmak yerine onları doğru analiz etmeyi başardığında ruhi doygunluğa erişebiliyor.\n\nÇok duyarlı bir burç olarak karşımıza çıkan balık empati duygusu en yüksek burçlar arasında yer alıyor. Duyarlılığı ile birlikte balık burcunun farkındalığı da yüksek. Uyumlu bir burç olan balık duygusal dünyasında birçok karmaşa yaşadığı için sosyal hayatında uzlaşmacı olmayı tercih ediliyor. Balık burcunun hayal gücü yüksek. Çoğu zaman hayal dünyasında kalmaktan keyif alan balık burcu gerçek dünya ile baş etmek konusunda zorlanıyor. Balık karşılaştığı olumsuzluklar karşısında yıkılacağını düşünerek hareket ediyor. Aslında mücadele gücü yüksek bir burç olan balık burcu özellikle kadınlarında duygusal çöküntüyü daha yüksek yaşama gerçekleşiyor. Erkeklerin duygusal çöküntüyü alaya alma metodları var. Balık erkekleri ile kadınları genel olarak benzerlik gösterse de küçük detaylarda farklılaşabiliyor. İki balık burcu kişi başta anlaşıp birbirlerini anladıklarını düşünebiliyor. Fakat bu bir yanılgı olarak karşımıza çıkıyor. İki balık burcu duygusal olarak beklentisi yüksek iki insan olarak anlaşmak konusunda uzun vadede sorun yaşayabiliyor. Balıklar oğlak ve koç gibi burçlarla arkadaşlık konusunda daha başarılı. İlişkilerde terazi gibi anlayışlı ve düşünceli burçlar ile daha uzun birliktelikler yaşayabiliyor. Balık  burcu erkek ve kadını akrep burcu kişileri yoğun şekilde çekici bulmasına rağmen onların pervasızlığı ile baş edemiyor. Balıklar hayatta duygularına göre hareket ederek ve bunu bir savunma mekanizması olarak kullanarak başarılı bir yaşam sürebiliyor. ",

  ];
}